[package]
name = "shy"
version = "0.6.3"
description = "A command line remote controller for MusicBee"
authors = ["fawn <fawn@envs.net>"]
license = "OSL-3.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11"
lazy_static = "1.4"

clap = { version = "4.1", features = ["cargo"] }
owo-colors = "3.5"
winapi = "0.3"
dirs = "4.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1"
roxmltree = "0.18"

[lib]
name = "shy"
path = "src/lib/lib.rs"

[[bin]]
name = "shy"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
codegen-units = 1
