[package]
name = "shy"
version = "0.7.4"
description = "A command line remote controller for MusicBee"
authors = ["fawn <fawn@envs.net>"]
license = "OSL-3.0"
repository = "https://github.com/fawni/shy"
keywords = ["musicbee"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.15", features = ["json"] }

clap = { version = "4.1.13", features = ["derive"] }
owo-colors = "3.5.0"
serde = { version = "1.0.158", features = ["derive"] }
miette = { version = "5.6.0", features = ["fancy"] }
winapi = "0.3.9"

dirs = "5.0.0"
urlencoding = "2.1.2"
roxmltree = "0.18.0"
once_cell = "1.17.1"

[dependencies.tokio]
features = ["macros", "fs", "rt-multi-thread", "parking_lot"]
version = "1.26.0"

[lib]
name = "shy"
path = "src/lib/lib.rs"

[[bin]]
name = "shy"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
codegen-units = 1
