name: "Run clippy lints"
on:
  push:
  pull_request:

jobs:
  run-clippy:
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          override: true
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "clippy"
      - name: "run clippy"
        run: "cargo clippy --locked -- -D warnings"
