name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Rust cache restore
        uses: "Swatinem/rust-cache@v1"
        with:
          key: cargo-x86_64-pc-windows-msvc-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --target x86_64-pc-windows-msvc --release --locked

      - name: Rename files
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          mkdir output/
          mv target/x86_64-pc-windows-msvc/release/shy.exe output/shy-$env:VERSION-x86_64-pc-windows-msvc.exe

      - name: Upload files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "output/*"
          token: ${{ secrets.GITHUB_TOKEN }}
